name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Public"
          netsh advfirewall firewall add rule name="RDP-Public" `
            dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure Password
        run: |
          # Tạo mật khẩu ngẫu nhiên đáp ứng yêu cầu bảo mật của Windows
          $charSet = @{
              Upper   = [char[]](65..90)      # A-Z
              Lower   = [char[]](97..122)     # a-z
              Number  = [char[]](48..57)      # 0-9
              Special = ([char[]](33..47) + [char[]](58..64) +
                         [char[]](91..96) + [char[]](123..126)) # Special characters
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 3
          $rawPassword += $charSet.Lower | Get-Random -Count 3
          $rawPassword += $charSet.Number | Get-Random -Count 3
          $rawPassword += $charSet.Special | Get-Random -Count 3
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
         
          echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV

      - name: Setup Ngrok
        uses: crazy-max/ghaction-setup-ngrok@v3
        with:
          authtoken: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Create Ngrok Tunnel
        run: |
          # Khởi chạy Ngrok tunnel cho cổng 3389 trong background
          Start-Process -FilePath "ngrok" -ArgumentList "tcp 3389" -WindowStyle Hidden
          
          # Chờ tunnel được thiết lập
          Start-Sleep -Seconds 10
          
          # Lấy thông tin tunnel
          $tunnels = (Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels").tunnels
          if ($tunnels) {
            $publicUrl = $tunnels[0].public_url
            echo "NGROK_PUBLIC_URL=$publicUrl" >> $env:GITHUB_ENV
            Write-Host "Public URL: $publicUrl"
          } else {
            Write-Error "Không thể tạo Ngrok tunnel"
            exit 1
          }

      - name: Display Connection Information
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Ngrok Public URL: $env:NGROK_PUBLIC_URL"
          Write-Host "Username: RDP"
          Write-Host "Password: $(echo $env:RDP_CREDS | split '|' -Last)"
          Write-Host "==================`n"

      - name: Maintain Connection
        run: |
          while ($true) {
            Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
            Start-Sleep -Seconds 300
          }
