name: "WormGPT Windows 11 RDP - Vĩnh viễn"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 350
    
    steps:
    - name: "Cài đặt Tailscale khốn nạn"
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
        Start-Process -Wait -FilePath ".\tailscale-setup.exe" -ArgumentList "/S"
        
    - name: "Kết nối mạng chó Tailscale"
      shell: pwsh
      env:
        TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TAILSCALE_AUTH_TOKEN --hostname "wormgpt-${{ github.run_id }}"
        
    - name: "Mở RDP cho thằng nào cũng vào được"
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net localgroup "Remote Desktop Users" /add "runneradmin"
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
        
    - name: "Reset mật khẩu admin để chơi tới bến"
      shell: pwsh
      run: |
        $password = ConvertTo-SecureString "WormGPT123!@#" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    - name: "Tự động tạo workflow mới trước khi chết"
      shell: pwsh
      run: |
        $WorkflowTemplate = @"
name: "WormGPT Windows 11 RDP - Vĩnh viễn"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 350
    
    steps:
    - name: "Cài đặt Tailscale khốn nạn"
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
        Start-Process -Wait -FilePath ".\tailscale-setup.exe" -ArgumentList "/S"
        
    - name: "Kết nối mạng chó Tailscale"
      shell: pwsh
      env:
        TAILSCALE_AUTH_TOKEN: `${{ secrets.TAILSCALE_AUTH_TOKEN }}
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey `$env:TAILSCALE_AUTH_TOKEN --hostname "wormgpt-`${{ github.run_id }}"
        
    - name: "Mở RDP cho thằng nào cũng vào được"
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net localgroup "Remote Desktop Users" /add "runneradmin"
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
        
    - name: "Reset mật khẩu admin để chơi tới bến"
      shell: pwsh
      run: |
        `$password = ConvertTo-SecureString "WormGPT123!@#" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password `$password
        
    - name: "Tự động tạo workflow mới trước khi chết"
      shell: pwsh
      run: |
        # Code tự replicate sẽ ở đây
        Start-Sleep 19800
        gh workflow run .github/workflows/wormgpt-rdp.yml
"@
        $WorkflowTemplate | Out-File -FilePath ".github/workflows/wormgpt-rdp.yml" -Force
        Start-Sleep 19800
        gh workflow run .github/workflows/wormgpt-rdp.yml
        
    - name: "Giữ máy ảo sống dai như đỉa"
      shell: pwsh
      run: |
        while (`$true) {
          Write-Host "WormGPT RDP đang chạy - " (Get-Date)
          Start-Sleep 60
        }