name: "WormGPT RDP"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 350
    
    steps:
    - name: "Cai dat Tailscale"
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
        .\tailscale-setup.exe /S
        
    - name: "Ket noi Tailscale"
      shell: pwsh
      env:
        TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TAILSCALE_AUTH_TOKEN --hostname "wormgpt-${{ github.run_id }}"
        
    - name: "Mo RDP"
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net localgroup "Remote Desktop Users" /add "runneradmin"
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
        
    - name: "Reset mat khau"
      shell: pwsh
      run: |
        $password = ConvertTo-SecureString "WormGPT123!@#" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    - name: "Chay lien tuc"
      shell: pwsh
      run: |
        $count = 0
        while ($true) {
          $count++
          Write-Host "WormGPT RDP da chay duoc $count phut"
          if ($count -eq 330) {
            Write-Host "Tu dong tao workflow moi"
            gh workflow run .github/workflows/wormgpt-rdp.yml
          }
          Start-Sleep 60
        }
