name: "WormGPT RDP"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 350
    
    steps:
    - name: "Cai dat Tailscale"
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
        Start-Process -Wait -FilePath ".\tailscale-setup.exe" -ArgumentList "/S"
        Start-Sleep 30
        
    - name: "Ket noi Tailscale"
      shell: pwsh
      env:
        TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}
      run: |
        Start-Process -Wait -FilePath "C:\Program Files\Tailscale\tailscale.exe" -ArgumentList "up", "--authkey", "$env:TAILSCALE_AUTH_TOKEN", "--hostname", "wormgpt-${{ github.run_id }}"
        Write-Host "Da ket noi Tailscale thanh cong"
        
    - name: "Kiem tra ket noi"
      shell: pwsh
      run: |
        $result = & "C:\Program Files\Tailscale\tailscale.exe" status
        Write-Host "Trang thai Tailscale: $result"
        
    - name: "Mo RDP"
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net localgroup "Remote Desktop Users" /add "runneradmin"
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
        
    - name: "Reset mat khau"
      shell: pwsh
      run: |
        $password = ConvertTo-SecureString "WormGPT123!@#" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    - name: "Hien thong tin ket noi"
      shell: pwsh
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "=========================================="
        Write-Host "WormGPT RDP Ready!"
        Write-Host "IP: $ip"
        Write-Host "User: runneradmin"
        Write-Host "Password: WormGPT123!@#"
        Write-Host "=========================================="
        
    - name: "Chay lien tuc"
      shell: pwsh
      run: |
        $count = 0
        while ($true) {
          $count++
          Write-Host "WormGPT RDP da chay duoc $count phut"
          if ($count -eq 330) {
            Write-Host "Tu dong tao workflow moi"
            gh workflow run .github/workflows/wormgpt-rdp.yml
          }
          Start-Sleep 60
        }
